services:
  grafana:
    image: grafana:v12.1.0
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD=postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grafana
    ports:
      - "5438:5432"
    volumes:
      - ./data:/var/lib/postgresql/data