import { SelectableValue, TimeOption } from '@grafana/data';

export const quickOptions: TimeOption[] = [
  { from: 'now-5m', to: 'now', display: "time-picker.quick-options.now-5m|Last 5 minutes" },
  { from: 'now-15m', to: 'now', display: "time-picker.quick-options.now-15m|Last 15 minutes" },
  { from: 'now-30m', to: 'now', display: "time-picker.quick-options.now-30m|Last 30 minutes" },
  { from: 'now-1h', to: 'now', display: "time-picker.quick-options.now-1h|Last 1 hour" },
  { from: 'now-3h', to: 'now', display: "time-picker.quick-options.now-3h|Last 3 hours" },
  { from: 'now-6h', to: 'now', display: "time-picker.quick-options.now-6h|Last 6 hours" },
  { from: 'now-12h', to: 'now', display: "time-picker.quick-options.now-12h|Last 12 hours" },
  { from: 'now-24h', to: 'now', display: "time-picker.quick-options.now-24h|Last 24 hours" },
  { from: 'now-2d', to: 'now', display: "time-picker.quick-options.now-2d|Last 2 days" },
  { from: 'now-7d', to: 'now', display: "time-picker.quick-options.now-7d|Last 7 days" },
  { from: 'now-30d', to: 'now', display: "time-picker.quick-options.now-30d|Last 30 days" },
  // { from: 'now-90d', to: 'now', display: 'Last 90 days' },
  // { from: 'now-6M', to: 'now', display: 'Last 6 months' },
  // { from: 'now-1y', to: 'now', display: 'Last 1 year' },
  // { from: 'now-2y', to: 'now', display: 'Last 2 years' },
  // { from: 'now-5y', to: 'now', display: 'Last 5 years' },
  { from: 'now-1d/d', to: 'now-1d/d', display: "time-picker.quick-options.now-1d/d|Yesterday" },
  // { from: 'now-2d/d', to: 'now-2d/d', display: 'Day before yesterday' },
  // { from: 'now-7d/d', to: 'now-7d/d', display: 'This day last week' },
  { from: 'now-1w/w', to: 'now-1w/w', display: "time-picker.quick-options.now-1w/w|Previous week" },
  { from: 'now-1M/M', to: 'now-1M/M', display: "time-picker.quick-options.now-1M/M|Previous month" },
  // { from: 'now-1Q/fQ', to: 'now-1Q/fQ', display: 'Previous fiscal quarter' },
  // { from: 'now-1y/y', to: 'now-1y/y', display: 'Previous year' },
  // { from: 'now-1y/fy', to: 'now-1y/fy', display: 'Previous fiscal year' },
  { from: 'now/d', to: 'now/d', display: "time-picker.quick-options.now/d|Today" },
  // { from: 'now/d', to: 'now', display: 'Today so far' },
  { from: 'now/w', to: 'now/w', display: "time-picker.quick-options.now/w|This week" },
  // { from: 'now/w', to: 'now', display: 'This week so far' },
  { from: 'now/M', to: 'now/M', display: "time-picker.quick-options.now/M|This month" },
  // { from: 'now/M', to: 'now', display: 'This month so far' },
  // { from: 'now/y', to: 'now/y', display: 'This year' },
  // { from: 'now/y', to: 'now', display: 'This year so far' },
  // { from: 'now/fQ', to: 'now', display: 'This fiscal quarter so far' },
  // { from: 'now/fQ', to: 'now/fQ', display: 'This fiscal quarter' },
  // { from: 'now/fy', to: 'now', display: 'This fiscal year so far' },
  // { from: 'now/fy', to: 'now/fy', display: 'This fiscal year' },
];

export const mapQuickOptionToJPValue = {
  "Last 5 minutes": "過去5分",
  "Last 15 minutes": "過去15分",
  "Last 30 minutes": "過去30分",
  "Last 1 hour": "過去1時間",
  "Last 3 hours": "過去3時間",
  "Last 6 hours": "過去6時間",
  "Last 12 hours": "過去12時間",
  "Last 24 hours": "過去24時間",
  "Last 2 days": "過去2日",
  "Last 7 days": "過去7日",
  "Last 30 days": "過去30日",
  "Yesterday": "昨日",
  "Previous week": "先週",
  "Previous month": "先月",
  "Today": "今日",
  "This week": "今週",
  "This month": "今月",
}

export const monthOptions: Array<SelectableValue<number>> = [
  { label: 'January', value: 0 },
  { label: 'February', value: 1 },
  { label: 'March', value: 2 },
  { label: 'April', value: 3 },
  { label: 'May', value: 4 },
  { label: 'June', value: 5 },
  { label: 'July', value: 6 },
  { label: 'August', value: 7 },
  { label: 'September', value: 8 },
  { label: 'October', value: 9 },
  { label: 'November', value: 10 },
  { label: 'December', value: 11 },
];
